# Generated by Django 6.0 on 2025-12-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_name', models.CharField(max_length=255, unique=True)),
                ('meter_id', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('function_code', models.IntegerField()),
                ('last_successful_read', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('meter_name', models.CharField(max_length=255)),
                ('import_active_energy', models.FloatField(blank=True, null=True)),
                ('export_active_energy', models.FloatField(blank=True, null=True)),
                ('import_reactive_energy', models.FloatField(blank=True, null=True)),
                ('export_reactive_energy', models.FloatField(blank=True, null=True)),
                ('total_active_energy', models.FloatField(blank=True, null=True)),
                ('total_reactive_energy', models.FloatField(blank=True, null=True)),
                ('power_demand', models.FloatField(blank=True, null=True)),
                ('maximum_power_demand', models.FloatField(blank=True, null=True)),
                ('current_demand', models.FloatField(blank=True, null=True)),
                ('maximum_current_demand', models.FloatField(blank=True, null=True)),
                ('active_power_demand', models.FloatField(blank=True, null=True)),
                ('maximum_active_power_demand', models.FloatField(blank=True, null=True)),
                ('apparent_power_demand', models.FloatField(blank=True, null=True)),
                ('uploaded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'energy_readings',
                'indexes': [models.Index(fields=['meter_name', '-timestamp'], name='energy_read_meter_n_645ec0_idx'), models.Index(fields=['uploaded'], name='energy_read_uploade_efc103_idx')],
            },
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('meter_name', models.CharField(max_length=255)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('active_power', models.FloatField(blank=True, null=True)),
                ('apparent_power', models.FloatField(blank=True, null=True)),
                ('reactive_power', models.FloatField(blank=True, null=True)),
                ('power_factor', models.FloatField(blank=True, null=True)),
                ('phase_angle', models.FloatField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('uploaded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'power_readings',
                'indexes': [models.Index(fields=['meter_name', '-timestamp'], name='power_readi_meter_n_c1ad09_idx'), models.Index(fields=['uploaded'], name='power_readi_uploade_4a9d91_idx')],
            },
        ),
    ]
