# Generated by Django 5.2.11 on 2026-02-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_timescaledb_setup'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='energyreading',
            new_name='energy_read_timesta_019394_idx',
            old_name='energy_readings_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='powerreading',
            new_name='power_readi_timesta_f74d08_idx',
            old_name='power_readings_timestamp_idx',
        ),
    ]
